### ISSUE TITLE
vulkan-registry default value invalid on Windows

### ISSUE THREAD

**Issue by Lypheo** [haasn/libplacebo#75]
Building git master on Windows yields:

```
[1/29] Generating vulkan boilerplate with a custom command
FAILED: src/utils_gen.c
"C:/Users/saifu/AppData/Local/Programs/Python/Python38/python.exe" "../src/vulkan/utils_gen.py" "/usr/share/vulkan/registry/vk.xml" "src/utils_gen.c"
Traceback (most recent call last):
  File "../src/vulkan/utils_gen.py", line 94, in <module>
    registry = ET.parse(xmlfile)
  File "C:\Users\saifu\AppData\Local\Programs\Python\Python38\lib\xml\etree\ElementTree.py", line 1202, in parse
    tree.parse(source, parser)
  File "C:\Users\saifu\AppData\Local\Programs\Python\Python38\lib\xml\etree\ElementTree.py", line 584, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/vulkan/registry/vk.xml'
[8/29] Compiling C object src/25a6634@@placebo@sha/vulkan_gpu.c.obj
ninja: build stopped: subcommand failed.
```
due to the hardcoded unix file path. The correct path on Windows is ``%VULKAN_SDK%\share\vulkan\registry\vk.xml``. I realize the path can be manually specified, but a sane default for Windows would be nice nonetheless.

**Comment by haasn** [comment]
I'll try coming up with a better way of handling this (e.g. explicitly checking for file existence and providing a better error message, or picking a better default based on the platform)
