### ISSUE TITLE
commit dca1913c6ac81c455800868e8c5219626351a959 broke cross-compiling (mingw64)

### ISSUE THREAD

**Issue by hydra3333** [haasn/libplacebo#76]
Hello.

It looks like commit dca1913c6ac81c455800868e8c5219626351a959 broke cross-compiling 
(mingw64 under ubuntu 18.04.3 for a target x86_64)

The commit just prior, 65e5e17edffaf0b9b1adcd9ba90637a27641e59b, cross-compiles fine.

Perhaps this ? :-
https://github.com/haasn/libplacebo/commit/dca1913c6ac81c455800868e8c5219626351a959#diff-f2ff94c68cbdd606743b339aa68a4164

Log:

```
[18:40:48][INFO] Git Cloning 'https://github.com/haasn/libplacebo.git' to '/home/u/Desktop/_working/workdir/x86_64/libplacebo_git'
[18:40:48][DEBUG] git clone  --progress "https://github.com/haasn/libplacebo.git" "libplacebo_git.tmp"
[18:40:48][DEBUG] Running 'git clone  --progress "https://github.com/haasn/libplacebo.git" "libplacebo_git.tmp"' in '/home/u/Desktop/_working/workdir/x86_64'
Cloning into 'libplacebo_git.tmp'...
remote: Enumerating objects: 521, done.        
remote: Counting objects: 100% (521/521), done.        
remote: Compressing objects: 100% (384/384), done.        
remote: Total 7228 (delta 344), reused 311 (delta 136), pack-reused 6707        
Receiving objects: 100% (7228/7228), 2.29 MiB | 1.93 MiB/s, done.
Resolving deltas: 100% (5264/5264), done.
Changing dir from /home/u/Desktop/_working/workdir/x86_64 to libplacebo_git.tmp
[18:40:51][DEBUG] cd libplacebo_git.tmp
[18:40:51][DEBUG] GIT Checking out: dca1913c6ac81c455800868e8c5219626351a959
[18:40:51][DEBUG] git checkout dca1913c6ac81c455800868e8c5219626351a959
[18:40:51][DEBUG] Running 'git checkout dca1913c6ac81c455800868e8c5219626351a959' in '/home/u/Desktop/_working/workdir/x86_64/libplacebo_git.tmp'
Note: checking out 'dca1913c6ac81c455800868e8c5219626351a959'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at dca1913 vulkan: generate boilerplate instead of hand-writing it
Changing dir from /home/u/Desktop/_working/workdir/x86_64/libplacebo_git.tmp to ..
[18:40:51][DEBUG] cd ..
[18:40:51][DEBUG] mv "libplacebo_git.tmp" "libplacebo_git"
[18:40:51][DEBUG] Running 'mv "libplacebo_git.tmp" "libplacebo_git"' in '/home/u/Desktop/_working/workdir/x86_64'
[18:40:51][INFO] Finished GIT cloning 'https://github.com/haasn/libplacebo.git' to 'libplacebo_git'
Changing dir from /home/u/Desktop/_working/workdir/x86_64 to libplacebo_git
[18:40:51][DEBUG] cd libplacebo_git
[18:40:51][DEBUG] git clean -ffdx
[18:40:51][DEBUG] Running 'git clean -ffdx' in '/home/u/Desktop/_working/workdir/x86_64/libplacebo_git'
[18:40:51][DEBUG] git submodule foreach --recursive git clean -ffdx
[18:40:51][DEBUG] Running 'git submodule foreach --recursive git clean -ffdx' in '/home/u/Desktop/_working/workdir/x86_64/libplacebo_git'
[18:40:51][DEBUG] git reset --hard
[18:40:51][DEBUG] Running 'git reset --hard' in '/home/u/Desktop/_working/workdir/x86_64/libplacebo_git'
HEAD is now at dca1913 vulkan: generate boilerplate instead of hand-writing it
[18:40:51][DEBUG] git submodule foreach --recursive git reset --hard
[18:40:51][DEBUG] Running 'git submodule foreach --recursive git reset --hard' in '/home/u/Desktop/_working/workdir/x86_64/libplacebo_git'
[18:40:51][DEBUG] git submodule update --init --recursive
[18:40:51][DEBUG] Running 'git submodule update --init --recursive' in '/home/u/Desktop/_working/workdir/x86_64/libplacebo_git'
[18:40:51][DEBUG] self.fullWorkDir="/home/u/Desktop/_working/workdir"
[18:40:51][DEBUG] mkdir -pv "../000_backup_subfolder"
[18:40:51][DEBUG] Running 'mkdir -pv "../000_backup_subfolder"' in '/home/u/Desktop/_working/workdir/x86_64/libplacebo_git'
[18:40:51][DEBUG] Backing up source folder: tar -cjf ../000_backup_subfolder/libplacebo_git.from_extracted_folder.tar.bz2 ../libplacebo_git/
[18:40:51][DEBUG] Running 'tar -cjf ../000_backup_subfolder/libplacebo_git.from_extracted_folder.tar.bz2 ../libplacebo_git/' in '/home/u/Desktop/_working/workdir/x86_64/libplacebo_git'
tar: Removing leading `../' from member names
Changing dir from /home/u/Desktop/_working/workdir/x86_64/libplacebo_git to build
[18:40:51][DEBUG] cd build
[18:40:51][INFO] Running run_post_regexreplace-command: 'cp -nv "/usr/bin/pkg-config" "/home/u/Desktop/_working/workdir/toolchain/x86_64-w64-mingw32/bin/x86_64-w64-mingw32-pkg-config"'
[18:40:51][DEBUG] Running 'cp -nv "/usr/bin/pkg-config" "/home/u/Desktop/_working/workdir/toolchain/x86_64-w64-mingw32/bin/x86_64-w64-mingw32-pkg-config"' in '/home/u/Desktop/_working/workdir/x86_64/libplacebo_git/build'
[18:40:51][INFO] Meson'ing 'libplacebo' with: --prefix=/home/u/Desktop/_working/workdir/toolchain/x86_64-w64-mingw32/x86_64-w64-mingw32 --libdir=/home/u/Desktop/_working/workdir/toolchain/x86_64-w64-mingw32/x86_64-w64-mingw32/lib --default-library=static --buildtype=plain --backend=ninja --buildtype=release -Dvulkan=enabled -Dlcms=enabled -Dtests=false -Dbench=false --cross-file=/home/u/Desktop/_working/workdir/meson_environment.txt ./ ..
[18:40:51][DEBUG] meson --prefix=/home/u/Desktop/_working/workdir/toolchain/x86_64-w64-mingw32/x86_64-w64-mingw32 --libdir=/home/u/Desktop/_working/workdir/toolchain/x86_64-w64-mingw32/x86_64-w64-mingw32/lib --default-library=static --buildtype=plain --backend=ninja --buildtype=release -Dvulkan=enabled -Dlcms=enabled -Dtests=false -Dbench=false --cross-file=/home/u/Desktop/_working/workdir/meson_environment.txt ./ ..
[18:40:51][DEBUG] Running 'meson --prefix=/home/u/Desktop/_working/workdir/toolchain/x86_64-w64-mingw32/x86_64-w64-mingw32 --libdir=/home/u/Desktop/_working/workdir/toolchain/x86_64-w64-mingw32/x86_64-w64-mingw32/lib --default-library=static --buildtype=plain --backend=ninja --buildtype=release -Dvulkan=enabled -Dlcms=enabled -Dtests=false -Dbench=false --cross-file=/home/u/Desktop/_working/workdir/meson_environment.txt ./ ..' in '/home/u/Desktop/_working/workdir/x86_64/libplacebo_git/build'
The Meson build system
Version: 0.53.2
Source dir: /home/u/Desktop/_working/workdir/x86_64/libplacebo_git
Build dir: /home/u/Desktop/_working/workdir/x86_64/libplacebo_git/build
Build type: cross build
Project name: libplacebo
Project version: 2.66.0
Appending CFLAGS from environment: '  -O3  -fstack-protector-all  -D_FORTIFY_SOURCE=2  '
Appending LDFLAGS from environment: ['-O3', '-fstack-protector-all', '-D_FORTIFY_SOURCE=2']
Appending CPPFLAGS from environment: '  -O3  -fstack-protector-all  -D_FORTIFY_SOURCE=2  '
C compiler for the build machine: cc (gcc 7.5.0 "cc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0")
C linker for the build machine: cc ld.bfd 2.30
Appending CXXFLAGS from environment: '  -O3  -fstack-protector-all  -D_FORTIFY_SOURCE=2  '
Appending LDFLAGS from environment: ['-O3', '-fstack-protector-all', '-D_FORTIFY_SOURCE=2']
Appending CPPFLAGS from environment: '  -O3  -fstack-protector-all  -D_FORTIFY_SOURCE=2  '
C++ compiler for the build machine: c++ (gcc 7.5.0 "c++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0")
C++ linker for the build machine: c++ ld.bfd 2.30
C compiler for the host machine: x86_64-w64-mingw32-gcc (gcc 11.0.0 "x86_64-w64-mingw32-gcc (GCC) 11.0.0 20200517 (experimental)")
C linker for the host machine: x86_64-w64-mingw32-gcc ld.bfd 2.34
C++ compiler for the host machine: x86_64-w64-mingw32-g++ (gcc 11.0.0 "x86_64-w64-mingw32-g++ (GCC) 11.0.0 20200517 (experimental)")
C++ linker for the host machine: x86_64-w64-mingw32-g++ ld.bfd 2.34
Build machine cpu family: x86_64
Build machine cpu: x86_64
Host machine cpu family: x86_64
Host machine cpu: x86_64
Target machine cpu family: x86_64
Target machine cpu: x86_64
Program git found: YES (/usr/bin/git)
Compiler for C supports arguments -Wincompatible-pointer-types: YES 
Compiler for C supports link arguments -Wl,--exclude-libs=ALL: YES 
Program python3 found: YES (/usr/bin/python3)
Library m found: YES

|Executing subproject xtalloc method meson 
|
|Project name: xtalloc
|Project version: undefined
|C compiler for the build machine: cc (gcc 7.5.0 "cc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0")
|C linker for the build machine: cc ld.bfd 2.30
|C compiler for the host machine: x86_64-w64-mingw32-gcc (gcc 11.0.0 "x86_64-w64-mingw32-gcc (GCC) 11.0.0 20200517 (experimental)")
|C linker for the host machine: x86_64-w64-mingw32-gcc ld.bfd 2.34
|Run-time dependency threads found: YES
|Build targets in project: 1
|Subproject xtalloc finished.


|Executing subproject bstr method meson 
|
|Project name: bstr
|Project version: undefined
|C compiler for the build machine: cc (gcc 7.5.0 "cc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0")
|C linker for the build machine: cc ld.bfd 2.30
|C compiler for the host machine: x86_64-w64-mingw32-gcc (gcc 11.0.0 "x86_64-w64-mingw32-gcc (GCC) 11.0.0 20200517 (experimental)")
|C linker for the host machine: x86_64-w64-mingw32-gcc ld.bfd 2.34
|Build targets in project: 2
|Subproject bstr finished.

Found pkg-config: /home/u/Desktop/_working/workdir/toolchain/x86_64-w64-mingw32/bin/pkg-config (0.29.2)
Run-time dependency vulkan found: YES 1.2.141
Found CMake: /usr/bin/cmake (3.16.5)
Run-time dependency epoxy found: NO (tried pkgconfig and cmake)
Library shaderc_shared found: NO
Library shaderc_combined found: YES
Header <shaderc/shaderc.h> has symbol "shaderc_optimization_level_performance" with dependency -lshaderc_combined: YES 
Message: Skipping `glslang` because `shaderc` is available
Run-time dependency lcms2 found: YES 2.10
Configuring config.h using configuration
Configuring config_internal.h using configuration
Dependency threads found: YES unknown (cached)
Build targets in project: 4

libplacebo 2.66.0

  Subprojects
       bstr: YES
    xtalloc: YES

Found ninja-1.8.2 at /usr/bin/ninja
[18:40:52][INFO][NINJA] Building 'libplacebo' with 'build_options':  in /home/u/Desktop/_working/workdir/x86_64/libplacebo_git/build
[18:40:52][DEBUG] ninja -j 6 
[18:40:52][DEBUG] Running 'ninja -j 6 ' in '/home/u/Desktop/_working/workdir/x86_64/libplacebo_git/build'
[1/37] Compiling C object 'subprojects/bstr/0ab0a38@@bstr@sta/siphash.c.obj'.
[2/37] Compiling C object 'subprojects/xtalloc/f0d261a@@xtalloc@sta/xtalloc.c.obj'.
[3/37] Compiling C object 'subprojects/bstr/0ab0a38@@bstr@sta/format.c.obj'.
[4/37] Compiling C object 'subprojects/xtalloc/f0d261a@@xtalloc@sta/ta_utils.c.obj'.
[5/37] Compiling C object 'subprojects/xtalloc/f0d261a@@xtalloc@sta/ta.c.obj'.
[6/37] Linking static target subprojects/xtalloc/libxtalloc.a.
[7/37] Compiling C object 'src/25a6634@@placebo@sta/context.c.obj'.
[8/37] Generating vulkan boilerplate with a custom command.
FAILED: src/utils_gen.c 
/usr/bin/python3 ../src/vulkan/utils_gen.py /usr/share/vulkan/registry/vk.xml src/utils_gen.c
Traceback (most recent call last):
  File "../src/vulkan/utils_gen.py", line 67, in <module>
    registry = ET.parse(xmlfile)
  File "/usr/lib/python3.6/xml/etree/ElementTree.py", line 1196, in parse
    tree.parse(source, parser)
  File "/usr/lib/python3.6/xml/etree/ElementTree.py", line 586, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/vulkan/registry/vk.xml'
[9/37] Compiling C object 'subprojects/bstr/0ab0a38@@bstr@sta/bstr.c.obj'.
[10/37] Compiling C object 'src/25a6634@@placebo@sta/common.c.obj'.
[11/37] Compiling C object 'src/25a6634@@placebo@sta/colorspace.c.obj'.
[12/37] Compiling C object 'src/25a6634@@placebo@sta/dither.c.obj'.
[13/37] Compiling C object 'src/25a6634@@placebo@sta/dispatch.c.obj'.
ninja: build stopped: subcommand failed.
[18:40:52][ERROR] Error [1] running process: 'ninja -j 6 ' in '/home/u/Desktop/_working/workdir/x86_64/libplacebo_git/build'

```

**Comment by hydra3333** [comment]
PS the folder
`~/Desktop/_working/workdir/toolchain/x86_64-w64-mingw32/share`
does not contain vk.xml either, not folder `registry` nor folder `vulkan`

**Comment by haasn** [comment]
Pushed https://github.com/haasn/libplacebo/commit/c747430c38677982ceb97b80ceaeca454d4e4111, which may fix your issue (and if it doesn't, should at least more clearly communicate what must be done to fix it on your end)

**Comment by hydra3333** [comment]
Thank you.  Nearly works.  The file exists where pointed to with -D however an error occurs:
```
[4/37] Generating vulkan boilerplate with a custom command.
FAILED: src/utils_gen.c 
/usr/bin/python3 ../src/vulkan/utils_gen.py /home/u/Desktop/_working/workdir/toolchain/x86_64-w64-mingw32/x86_64-w64-mingw32/share/vulkan/registry/vk.xml src/utils_gen.c
Traceback (most recent call last):
  File "../src/vulkan/utils_gen.py", line 120, in <module>
    if not xmlfile or xmfile == '':
NameError: name 'xmfile' is not defined
```

Log:
```
[01:40:53][INFO] Meson'ing 'libplacebo' with: --prefix=/home/u/Desktop/_working/workdir/toolchain/x86_64-w64-mingw32/x86_64-w64-mingw32 --libdir=/home/u/Desktop/_working/workdir/toolchain/x86_64-w64-mingw32/x86_64-w64-mingw32/lib --default-library=static --buildtype=plain --backend=ninja --buildtype=release -Dvulkan=enabled -Dvulkan-registry=/home/u/Desktop/_working/workdir/toolchain/x86_64-w64-mingw32/x86_64-w64-mingw32/share/vulkan/registry/vk.xml -Dlcms=enabled -Dtests=false -Dbench=false --cross-file=/home/u/Desktop/_working/workdir/meson_environment.txt ./ ..
[01:40:53][DEBUG] meson --prefix=/home/u/Desktop/_working/workdir/toolchain/x86_64-w64-mingw32/x86_64-w64-mingw32 --libdir=/home/u/Desktop/_working/workdir/toolchain/x86_64-w64-mingw32/x86_64-w64-mingw32/lib --default-library=static --buildtype=plain --backend=ninja --buildtype=release -Dvulkan=enabled -Dvulkan-registry=/home/u/Desktop/_working/workdir/toolchain/x86_64-w64-mingw32/x86_64-w64-mingw32/share/vulkan/registry/vk.xml -Dlcms=enabled -Dtests=false -Dbench=false --cross-file=/home/u/Desktop/_working/workdir/meson_environment.txt ./ ..
[01:40:53][DEBUG] Running 'meson --prefix=/home/u/Desktop/_working/workdir/toolchain/x86_64-w64-mingw32/x86_64-w64-mingw32 --libdir=/home/u/Desktop/_working/workdir/toolchain/x86_64-w64-mingw32/x86_64-w64-mingw32/lib --default-library=static --buildtype=plain --backend=ninja --buildtype=release -Dvulkan=enabled -Dvulkan-registry=/home/u/Desktop/_working/workdir/toolchain/x86_64-w64-mingw32/x86_64-w64-mingw32/share/vulkan/registry/vk.xml -Dlcms=enabled -Dtests=false -Dbench=false --cross-file=/home/u/Desktop/_working/workdir/meson_environment.txt ./ ..' in '/home/u/Desktop/_working/workdir/x86_64/libplacebo_git/build'
The Meson build system
Version: 0.53.2
Source dir: /home/u/Desktop/_working/workdir/x86_64/libplacebo_git
Build dir: /home/u/Desktop/_working/workdir/x86_64/libplacebo_git/build
Build type: cross build
Project name: libplacebo
Project version: 2.72.0
Appending CFLAGS from environment: '  -O3  -fstack-protector-all  -D_FORTIFY_SOURCE=2  '
Appending LDFLAGS from environment: ['-O3', '-fstack-protector-all', '-D_FORTIFY_SOURCE=2']
Appending CPPFLAGS from environment: '  -O3  -fstack-protector-all  -D_FORTIFY_SOURCE=2  '
C compiler for the build machine: cc (gcc 7.5.0 "cc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0")
C linker for the build machine: cc ld.bfd 2.30
Appending CXXFLAGS from environment: '  -O3  -fstack-protector-all  -D_FORTIFY_SOURCE=2  '
Appending LDFLAGS from environment: ['-O3', '-fstack-protector-all', '-D_FORTIFY_SOURCE=2']
Appending CPPFLAGS from environment: '  -O3  -fstack-protector-all  -D_FORTIFY_SOURCE=2  '
C++ compiler for the build machine: c++ (gcc 7.5.0 "c++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0")
C++ linker for the build machine: c++ ld.bfd 2.30
C compiler for the host machine: x86_64-w64-mingw32-gcc (gcc 11.0.0 "x86_64-w64-mingw32-gcc (GCC) 11.0.0 20200517 (experimental)")
C linker for the host machine: x86_64-w64-mingw32-gcc ld.bfd 2.34
C++ compiler for the host machine: x86_64-w64-mingw32-g++ (gcc 11.0.0 "x86_64-w64-mingw32-g++ (GCC) 11.0.0 20200517 (experimental)")
C++ linker for the host machine: x86_64-w64-mingw32-g++ ld.bfd 2.34
Build machine cpu family: x86_64
Build machine cpu: x86_64
Host machine cpu family: x86_64
Host machine cpu: x86_64
Target machine cpu family: x86_64
Target machine cpu: x86_64
Program git found: YES (/usr/bin/git)
Compiler for C supports arguments -Wincompatible-pointer-types: YES 
Compiler for C supports link arguments -Wl,--exclude-libs=ALL: YES 
Program python3 found: YES (/usr/bin/python3)
Library m found: YES

|Executing subproject xtalloc method meson 
|
|Project name: xtalloc
|Project version: undefined
|C compiler for the build machine: cc (gcc 7.5.0 "cc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0")
|C linker for the build machine: cc ld.bfd 2.30
|C compiler for the host machine: x86_64-w64-mingw32-gcc (gcc 11.0.0 "x86_64-w64-mingw32-gcc (GCC) 11.0.0 20200517 (experimental)")
|C linker for the host machine: x86_64-w64-mingw32-gcc ld.bfd 2.34
|Run-time dependency threads found: YES
|Build targets in project: 1
|Subproject xtalloc finished.


|Executing subproject bstr method meson 
|
|Project name: bstr
|Project version: undefined
|C compiler for the build machine: cc (gcc 7.5.0 "cc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0")
|C linker for the build machine: cc ld.bfd 2.30
|C compiler for the host machine: x86_64-w64-mingw32-gcc (gcc 11.0.0 "x86_64-w64-mingw32-gcc (GCC) 11.0.0 20200517 (experimental)")
|C linker for the host machine: x86_64-w64-mingw32-gcc ld.bfd 2.34
|Build targets in project: 2
|Subproject bstr finished.

Found pkg-config: /home/u/Desktop/_working/workdir/toolchain/x86_64-w64-mingw32/bin/pkg-config (0.29.2)
Run-time dependency vulkan found: YES 1.2.141
Found CMake: /usr/bin/cmake (3.16.5)
Run-time dependency epoxy found: NO (tried pkgconfig and cmake)
Library shaderc_shared found: NO
Library shaderc_combined found: YES
Header <shaderc/shaderc.h> has symbol "shaderc_optimization_level_performance" with dependency -lshaderc_combined: YES 
Message: Skipping `glslang` because `shaderc` is available
Run-time dependency lcms2 found: YES 2.10
Configuring config.h using configuration
Configuring config_internal.h using configuration
Dependency threads found: YES unknown (cached)
Build targets in project: 4

libplacebo 2.72.0

  Subprojects
       bstr: YES
    xtalloc: YES

Found ninja-1.8.2 at /usr/bin/ninja
[01:40:54][INFO][NINJA] Building 'libplacebo' with 'build_options':  in /home/u/Desktop/_working/workdir/x86_64/libplacebo_git/build
[01:40:54][DEBUG] ninja -j 6 
[01:40:54][DEBUG] Running 'ninja -j 6 ' in '/home/u/Desktop/_working/workdir/x86_64/libplacebo_git/build'
[1/37] Compiling C object 'subprojects/xtalloc/f0d261a@@xtalloc@sta/xtalloc.c.obj'.
[2/37] Compiling C object 'subprojects/bstr/0ab0a38@@bstr@sta/siphash.c.obj'.
[3/37] Compiling C object 'subprojects/xtalloc/f0d261a@@xtalloc@sta/ta_utils.c.obj'.
[4/37] Generating vulkan boilerplate with a custom command.
FAILED: src/utils_gen.c 
/usr/bin/python3 ../src/vulkan/utils_gen.py /home/u/Desktop/_working/workdir/toolchain/x86_64-w64-mingw32/x86_64-w64-mingw32/share/vulkan/registry/vk.xml src/utils_gen.c
Traceback (most recent call last):
  File "../src/vulkan/utils_gen.py", line 120, in <module>
    if not xmlfile or xmfile == '':
NameError: name 'xmfile' is not defined
[5/37] Compiling C object 'subprojects/bstr/0ab0a38@@bstr@sta/format.c.obj'.
[6/37] Compiling C object 'subprojects/xtalloc/f0d261a@@xtalloc@sta/ta.c.obj'.
[7/37] Compiling C object 'subprojects/bstr/0ab0a38@@bstr@sta/bstr.c.obj'.
[8/37] Compiling C object 'src/25a6634@@placebo@sta/colorspace.c.obj'.
[9/37] Compiling C object 'src/25a6634@@placebo@sta/common.c.obj'.
ninja: build stopped: subcommand failed.
[01:40:54][ERROR] Error [1] running process: 'ninja -j 6 ' in '/home/u/Desktop/_working/workdir/x86_64/libplacebo_git/build'


~/Desktop/_working$ ls -al /home/u/Desktop/_working/workdir/toolchain/x86_64-w64-mingw32/x86_64-w64-mingw32/share/vulkan/registry/vk.xml
-rw-r--r-- 1 u u 1236908 May 29 20:12 /home/u/Desktop/_working/workdir/toolchain/x86_64-w64-mingw32/x86_64-w64-mingw32/share/vulkan/registry/vk.xml

```
