### ISSUE TITLE
error thrown by utils_gen.py

### ISSUE THREAD

**Issue by hydra3333** [haasn/libplacebo#77]
Hello, just tried to build libplacebo and am receiving the error shown at the bottom of the log below.

```
[13:27:26][INFO] Meson'ing 'libplacebo' with: --prefix=/home/u/Desktop/_working/workdir/toolchain/x86_64-w64-mingw32/x86_64-w64-mingw32 --libdir=/home/u/Desktop/_working/workdir/toolchain/x86_64-w64-mingw32/x86_64-w64-mingw32/lib --default-library=static --buildtype=plain --backend=ninja --buildtype=release -Dvulkan=enabled -Dvulkan-registry=/home/u/Desktop/_working/workdir/toolchain/x86_64-w64-mingw32/x86_64-w64-mingw32/share/vulkan/registry/vk.xml -Dlcms=enabled -Dtests=false -Dbench=false --cross-file=/home/u/Desktop/_working/workdir/meson_environment.txt ./ ..
[13:27:26][DEBUG] meson --prefix=/home/u/Desktop/_working/workdir/toolchain/x86_64-w64-mingw32/x86_64-w64-mingw32 --libdir=/home/u/Desktop/_working/workdir/toolchain/x86_64-w64-mingw32/x86_64-w64-mingw32/lib --default-library=static --buildtype=plain --backend=ninja --buildtype=release -Dvulkan=enabled -Dvulkan-registry=/home/u/Desktop/_working/workdir/toolchain/x86_64-w64-mingw32/x86_64-w64-mingw32/share/vulkan/registry/vk.xml -Dlcms=enabled -Dtests=false -Dbench=false --cross-file=/home/u/Desktop/_working/workdir/meson_environment.txt ./ ..
[13:27:26][DEBUG] Running 'meson --prefix=/home/u/Desktop/_working/workdir/toolchain/x86_64-w64-mingw32/x86_64-w64-mingw32 --libdir=/home/u/Desktop/_working/workdir/toolchain/x86_64-w64-mingw32/x86_64-w64-mingw32/lib --default-library=static --buildtype=plain --backend=ninja --buildtype=release -Dvulkan=enabled -Dvulkan-registry=/home/u/Desktop/_working/workdir/toolchain/x86_64-w64-mingw32/x86_64-w64-mingw32/share/vulkan/registry/vk.xml -Dlcms=enabled -Dtests=false -Dbench=false --cross-file=/home/u/Desktop/_working/workdir/meson_environment.txt ./ ..' in '/home/u/Desktop/_working/workdir/x86_64/libplacebo_git/build'
The Meson build system
Version: 0.53.2
Source dir: /home/u/Desktop/_working/workdir/x86_64/libplacebo_git
Build dir: /home/u/Desktop/_working/workdir/x86_64/libplacebo_git/build
Build type: cross build
Project name: libplacebo
Project version: 2.72.0
Appending CFLAGS from environment: '  -O3  -fstack-protector-all  -D_FORTIFY_SOURCE=2  '
Appending LDFLAGS from environment: ['-O3', '-fstack-protector-all', '-D_FORTIFY_SOURCE=2']
Appending CPPFLAGS from environment: '  -O3  -fstack-protector-all  -D_FORTIFY_SOURCE=2  '
C compiler for the build machine: cc (gcc 7.5.0 "cc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0")
C linker for the build machine: cc ld.bfd 2.30
Appending CXXFLAGS from environment: '  -O3  -fstack-protector-all  -D_FORTIFY_SOURCE=2  '
Appending LDFLAGS from environment: ['-O3', '-fstack-protector-all', '-D_FORTIFY_SOURCE=2']
Appending CPPFLAGS from environment: '  -O3  -fstack-protector-all  -D_FORTIFY_SOURCE=2  '
C++ compiler for the build machine: c++ (gcc 7.5.0 "c++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0")
C++ linker for the build machine: c++ ld.bfd 2.30
C compiler for the host machine: x86_64-w64-mingw32-gcc (gcc 11.0.0 "x86_64-w64-mingw32-gcc (GCC) 11.0.0 20200517 (experimental)")
C linker for the host machine: x86_64-w64-mingw32-gcc ld.bfd 2.34
C++ compiler for the host machine: x86_64-w64-mingw32-g++ (gcc 11.0.0 "x86_64-w64-mingw32-g++ (GCC) 11.0.0 20200517 (experimental)")
C++ linker for the host machine: x86_64-w64-mingw32-g++ ld.bfd 2.34
Build machine cpu family: x86_64
Build machine cpu: x86_64
Host machine cpu family: x86_64
Host machine cpu: x86_64
Target machine cpu family: x86_64
Target machine cpu: x86_64
Program git found: YES (/usr/bin/git)
Compiler for C supports arguments -Wincompatible-pointer-types: YES 
Compiler for C supports link arguments -Wl,--exclude-libs=ALL: YES 
Program python3 found: YES (/usr/bin/python3)
Library m found: YES

|Executing subproject xtalloc method meson 
|
|Project name: xtalloc
|Project version: undefined
|C compiler for the build machine: cc (gcc 7.5.0 "cc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0")
|C linker for the build machine: cc ld.bfd 2.30
|C compiler for the host machine: x86_64-w64-mingw32-gcc (gcc 11.0.0 "x86_64-w64-mingw32-gcc (GCC) 11.0.0 20200517 (experimental)")
|C linker for the host machine: x86_64-w64-mingw32-gcc ld.bfd 2.34
|Run-time dependency threads found: YES
|Build targets in project: 1
|Subproject xtalloc finished.


|Executing subproject bstr method meson 
|
|Project name: bstr
|Project version: undefined
|C compiler for the build machine: cc (gcc 7.5.0 "cc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0")
|C linker for the build machine: cc ld.bfd 2.30
|C compiler for the host machine: x86_64-w64-mingw32-gcc (gcc 11.0.0 "x86_64-w64-mingw32-gcc (GCC) 11.0.0 20200517 (experimental)")
|C linker for the host machine: x86_64-w64-mingw32-gcc ld.bfd 2.34
|Build targets in project: 2
|Subproject bstr finished.

Found pkg-config: /home/u/Desktop/_working/workdir/toolchain/x86_64-w64-mingw32/bin/pkg-config (0.29.2)
Run-time dependency vulkan found: YES 1.2.141
Found CMake: /usr/bin/cmake (3.16.5)
Run-time dependency epoxy found: NO (tried pkgconfig and cmake)
Library shaderc_shared found: NO
Library shaderc_combined found: YES
Header <shaderc/shaderc.h> has symbol "shaderc_optimization_level_performance" with dependency -lshaderc_combined: YES 
Message: Skipping `glslang` because `shaderc` is available
Run-time dependency lcms2 found: YES 2.10
Configuring config.h using configuration
Configuring config_internal.h using configuration
Dependency threads found: YES unknown (cached)
Build targets in project: 4

libplacebo 2.72.0

  Subprojects
       bstr: YES
    xtalloc: YES

Found ninja-1.8.2 at /usr/bin/ninja
[13:27:27][INFO][NINJA] Building 'libplacebo' with 'build_options': '' in '/home/u/Desktop/_working/workdir/x86_64/libplacebo_git/build'
[13:27:27][DEBUG] ninja -j 6 
[13:27:27][DEBUG] Running 'ninja -j 6 ' in '/home/u/Desktop/_working/workdir/x86_64/libplacebo_git/build'
[1/37] Compiling C object 'subprojects/bstr/0ab0a38@@bstr@sta/siphash.c.obj'.
[2/37] Compiling C object 'subprojects/xtalloc/f0d261a@@xtalloc@sta/xtalloc.c.obj'.
[3/37] Compiling C object 'subprojects/xtalloc/f0d261a@@xtalloc@sta/ta_utils.c.obj'.
[4/37] Compiling C object 'subprojects/bstr/0ab0a38@@bstr@sta/format.c.obj'.
[5/37] Compiling C object 'subprojects/xtalloc/f0d261a@@xtalloc@sta/ta.c.obj'.
[6/37] Linking static target subprojects/xtalloc/libxtalloc.a.
[7/37] Generating vulkan boilerplate with a custom command.
FAILED: src/utils_gen.c 
/usr/bin/python3 ../src/vulkan/utils_gen.py /home/u/Desktop/_working/workdir/toolchain/x86_64-w64-mingw32/x86_64-w64-mingw32/share/vulkan/registry/vk.xml src/utils_gen.c
Traceback (most recent call last):
  File "/usr/lib/python3.6/xml/etree/ElementPath.py", line 263, in iterfind
    selector = _cache[cache_key]
KeyError: ('member/name[.="sType"]/..', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../src/vulkan/utils_gen.py", line 128, in <module>
    vkstructs = get_vkstructs(registry),
  File "/usr/lib/python3/dist-packages/mako/template.py", line 462, in render
    return runtime._render(self, self.callable_, args, data)
  File "/usr/lib/python3/dist-packages/mako/runtime.py", line 838, in _render
    **_kwargs_for_callable(callable_, data))
  File "/usr/lib/python3/dist-packages/mako/runtime.py", line 873, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/usr/lib/python3/dist-packages/mako/runtime.py", line 899, in _exec_template
    callable_(context, *args, **kwargs)
  File "memory:0x7f137887a6d8", line 38, in render_body
  File "../src/vulkan/utils_gen.py", line 92, in get_vkstructs
    stype = e.find('member/name[.="sType"]/..')
  File "/usr/lib/python3.6/xml/etree/ElementPath.py", line 298, in find
    return next(iterfind(elem, path, namespaces), None)
  File "/usr/lib/python3.6/xml/etree/ElementPath.py", line 277, in iterfind
    selector.append(ops[token[0]](next, token))
  File "/usr/lib/python3.6/xml/etree/ElementPath.py", line 233, in prepare_predicate
    raise SyntaxError("invalid predicate")
SyntaxError: invalid predicate
[8/37] Compiling C object 'subprojects/bstr/0ab0a38@@bstr@sta/bstr.c.obj'.
[9/37] Compiling C object 'src/25a6634@@placebo@sta/context.c.obj'.
[10/37] Compiling C object 'src/25a6634@@placebo@sta/common.c.obj'.
[11/37] Compiling C object 'src/25a6634@@placebo@sta/colorspace.c.obj'.
[12/37] Compiling C object 'src/25a6634@@placebo@sta/dither.c.obj'.
ninja: build stopped: subcommand failed.
```

**Comment by haasn** [comment]
Can you upload your vk.xml?

**Comment by hydra3333** [comment]
Sure. It's the one created (subsequently untouched) by installing vulkan_headers.
Good luck.
[vk.xml.txt](https://github.com/haasn/libplacebo/files/4705752/vk.xml.txt)

**Comment by haasn** [comment]
Seems to be caused by the use of python3.6. It works if I set it to python3.7 or newer.

I'll try seeing if I can make it backwards compatible.

**Comment by hydra3333** [comment]
Thank you.

**Comment by hydra3333** [comment]
confirming success. thank you.
